### ISSUE TITLE
Filters dont work

### ISSUE THREAD

**Issue by marks** [ckan/ckanext-dashboard#11]
I apply filters to my dashboard with just a grid (1251-resource-view branch) but see in the AJAX requests on the dashboard page and in my ckan server logs that no filters were applied to the grid. Excerpt from server log:

```
2014-05-09 18:55:09,405 DEBUG [ckan.lib.base] Retrieving request params: UnicodeMultiDict([('{"resource_id":"c0d9ab3c-91a3-4fe8-8f54-5d3009e4f01d","q":"","filters":{},"limit":100,"offset":0}', u'')])
```

I'm looking into how to fix this if I can; any pointers appreciated

**Comment by marks** [comment]
I think I have narrowed this down to the fact that https://github.com/ckan/ckan/blob/1251-resource-view/ckanext/reclinepreview/theme/public/preview_recline.js#L57 does not take the URL parameters  into account. Will keep working on this later... hopefully it's not just me having this issue

**Comment by marks** [comment]
A quick note on progress - I've been able to get this to work for grids (havent tried others) by adding the following to `/ckan/ckanext/reclinepreview/theme/public/preview_recline.js` right after `dataset = new recline.Model.Dataset(resourceData);`

``` javascript
      var query = new recline.Model.Query();
      query.set({ size : reclineView.limit || 100 })
      query.set({ from : reclineView.offset || 0 })
      if(window.parent.ckan.views && window.parent.ckan.views.viewhelpers.filters._searchParams.filters){
        $.each(window.parent.ckan.views.viewhelpers.filters._searchParams.filters, function(field,values){
          query.addFilter({type: 'term', field: field, term: values})
        })
      }
```

Honestly not sure if this is even right yet but I figured I'd update anyone else who finds this with the latest

**Comment by vitorbaptista** [comment]
@marks You're on the right track. The problem is that `recline_grid` doesn't recognize filters.

I'm leaning making the `viewhelpers` default on CKAN, as I think at least the `filters` are very useful for many visualizations. I haven't made my mind yet, but this use case might be another reason to make it default.

Anyway, for your patch, instead of messing up with `_searchParams`, use `ckan.views.viewhelpers.filters.get()`. If you don't pass parameters, it'll return every filter (or an empty object if there're no filters).

If you don't need every functionality Recline's grid has (unlikely, I guess), there's the `basicgrid` plugin on `ckanext-basiccharts`, that accepts filters.

**Comment by marks** [comment]
@vitorbaptista I just posted https://github.com/marks/ckan/commit/daab700886999a3e4214c3fc93f9bd38d887c037 - not sure if you'd want to merge this into master just yet but it does seem to do the trick for me for now. if this part of the code is covered by tests, please do give me a pointer of where to look and i'll work on that too.

**Comment by vitorbaptista** [comment]
@marks I got your commit into https://github.com/ckan/ckan/pull/1251 . Thanks!
